### ISSUE TITLE
Dissociation genes counted multiple times

### ISSUE THREAD

**Issue by rdistefano** [bicciatolab/PoPsicleR#2]
Digging down the QC metrics calculated by PopsicleR (compared Scanpy vs. PopsincleR), I found a potential error in the _percent_disso_ calculation. A few genes are counted multiple times. I would suggest going from:  

`dissociation_genes <- paste(dissociation_genes, collapse='|')
`

to

`dissociation_genes <- paste('^', paste(dissociation_genes, collapse='$|^'), '$', sep = '')
`

Please, check this out.

**Comment by bicciatolab** [comment]
Dear Rosario, thank you for reporting this issue and for your kind suggestion.

We tested popsicleR on some different datasets and found that in some cases few genes could be counted multiple times as you noted.

We have already implemented your solution in our code and updated the package.

Thank you for your support.
