### ISSUE TITLE
MakeAnnotation erro, Error in `collect()`: ! Failed to collect lazy table.

### ISSUE THREAD

**Issue by luying616** [bicciatolab/PoPsicleR#4]
# Cell type annotation
sample.umi <- MakeAnnotation(UMI = sample.umi, organism = "human", marker.list = "none", cluster_res= 0.8, out_folder = main.dir)

Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Backtrace:
  1. popsicleR::MakeAnnotation(...)
 18. dbplyr:::collect.tbl_sql(., Inf)
 23. dbplyr::db_collect(x$src$con, sql, n = n, warn_incomplete = warn_incomplete, ...)
Error in collect(., Inf) :
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?

─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31)
 os       CentOS Linux 7 (Core)
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Asia/Shanghai
 date     2024-03-22
 rstudio  2023.06.1+524 Mountain Hydrangea (server)
 pandoc   3.1.1 @ /usr/lib/rstudio-server/bin/quarto/bin/tools/ (via rmarkdown)

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 package                * version   date (UTC) lib source
 abind                    1.4-5     2016-07-21 [1] CRAN (R 4.2.1)
 annotate               * 1.76.0    2022-11-01 [1] Bioconductor
 AnnotationDbi          * 1.60.2    2023-03-10 [1] Bioconductor
 AnnotationHub            3.6.0     2022-11-01 [1] Bioconductor
 ape                    * 5.7-1     2023-03-13 [1] CRAN (R 4.2.2)
 askpass                  1.1       2019-01-13 [1] CRAN (R 4.2.1)
 AUCell                 * 1.20.2    2022-12-01 [1] Bioconductor
 beachmat                 2.14.0    2022-11-01 [1] Bioconductor
 beeswarm                 0.4.0     2021-06-01 [1] CRAN (R 4.2.1)
 Biobase                * 2.58.0    2022-11-01 [1] Bioconductor
 BiocFileCache            2.6.1     2023-02-17 [1] Bioconductor
 BiocGenerics           * 0.44.0    2022-11-01 [1] Bioconductor
 BiocIO                   1.8.0     2022-11-01 [1] Bioconductor
 BiocManager              1.30.22   2023-08-08 [1] CRAN (R 4.2.2)
 BiocNeighbors            1.16.0    2022-11-01 [1] Bioconductor
 BiocParallel             1.32.6    2023-03-17 [1] Bioconductor
 BiocSingular             1.14.0    2022-11-01 [1] Bioconductor
 BiocVersion              3.16.0    2022-04-26 [1] Bioconductor
 Biostrings               2.66.0    2022-11-01 [1] Bioconductor
 bit                      4.0.5     2022-11-15 [1] CRAN (R 4.2.2)
 bit64                    4.0.5     2020-08-30 [1] CRAN (R 4.2.1)
 bitops                   1.0-7     2021-04-24 [1] CRAN (R 4.2.1)
 blob                     1.2.4     2023-03-17 [1] CRAN (R 4.2.3)
 bluster                  1.8.0     2022-11-01 [1] Bioconductor
 bsselectR              * 0.1.0     2024-03-21 [1] Github (walkerke/bsselectR@c196e8f)
 cachem                   1.0.7     2023-02-24 [1] CRAN (R 4.2.2)
 celldex                * 1.8.0     2022-11-03 [1] Bioconductor
 cellranger               1.1.0     2016-07-27 [1] CRAN (R 4.2.1)
 circlize                 0.4.16    2024-02-20 [1] CRAN (R 4.2.2)
 cli                      3.6.1     2023-03-23 [1] CRAN (R 4.2.3)
 cluster                * 2.1.6     2023-12-01 [1] CRAN (R 4.2.2)
 clustree               * 0.5.1     2023-11-05 [1] CRAN (R 4.2.2)
 codetools                0.2-19    2023-02-01 [1] CRAN (R 4.2.2)
 colorspace               2.1-0     2023-01-23 [1] CRAN (R 4.2.2)
 corrplot               * 0.92      2021-11-18 [1] CRAN (R 4.2.2)
 cowplot                  1.1.3     2024-01-22 [1] CRAN (R 4.2.2)
 crayon                 * 1.5.2     2022-09-29 [1] CRAN (R 4.2.1)
 curl                     5.0.0     2023-01-12 [1] CRAN (R 4.2.3)
 data.table             * 1.14.10   2023-12-08 [1] CRAN (R 4.2.2)
 DBI                      1.2.2     2024-02-16 [1] CRAN (R 4.2.2)
 dbplyr                   2.4.0     2023-10-26 [1] CRAN (R 4.2.2)
 DelayedArray             0.24.0    2022-11-01 [1] Bioconductor
 DelayedMatrixStats       1.20.0    2022-11-01 [1] Bioconductor
 deldir                   1.0-6     2021-10-23 [1] CRAN (R 4.2.1)
 devtools               * 2.4.5     2022-10-11 [1] CRAN (R 4.2.2)
 DiagrammeR             * 1.0.11    2024-02-02 [1] CRAN (R 4.2.2)
 digest                   0.6.31    2022-12-11 [1] CRAN (R 4.2.2)
 doParallel               1.0.17    2022-02-07 [1] CRAN (R 4.2.2)
 downloadthis           * 0.3.3     2023-11-09 [1] CRAN (R 4.2.2)
 dplyr                  * 1.1.3     2023-09-03 [1] CRAN (R 4.2.2)
 dqrng                    0.3.0     2021-05-01 [1] CRAN (R 4.2.1)
 DropletUtils           * 1.18.1    2022-11-22 [1] Bioconductor
 DT                     * 0.32      2024-02-19 [1] CRAN (R 4.2.2)
 edgeR                    3.40.2    2023-01-19 [1] Bioconductor
 ellipsis                 0.3.2     2021-04-29 [1] CRAN (R 4.2.1)
 EnhancedVolcano          1.16.0    2022-11-01 [1] Bioconductor
 evaluate                 0.23      2023-11-01 [1] CRAN (R 4.2.2)
 ExperimentHub            2.6.0     2022-11-01 [1] Bioconductor
 fansi                    1.0.4     2023-01-22 [1] CRAN (R 4.2.2)
 farver                   2.1.1     2022-07-06 [1] CRAN (R 4.2.1)
 fastmap                  1.1.1     2023-02-24 [1] CRAN (R 4.2.2)
 filelock                 1.0.2     2018-10-05 [1] CRAN (R 4.2.2)
 fitdistrplus             1.1-11    2023-04-25 [1] CRAN (R 4.2.2)
 foreach                  1.5.2     2022-02-02 [1] CRAN (R 4.2.3)
 fs                       1.6.1     2023-02-06 [1] CRAN (R 4.2.2)
 future                 * 1.33.1    2023-12-22 [1] CRAN (R 4.2.2)
 future.apply             1.11.1    2023-12-21 [1] CRAN (R 4.2.2)
 generics                 0.1.3     2022-07-05 [1] CRAN (R 4.2.1)
 GenomeInfoDb           * 1.34.9    2023-02-02 [1] Bioconductor
 GenomeInfoDbData         1.2.9     2023-03-21 [1] Bioconductor
 GenomicAlignments        1.34.1    2023-03-09 [1] Bioconductor
 GenomicRanges          * 1.50.2    2022-12-16 [1] Bioconductor
 GEOquery               * 2.66.0    2022-11-01 [1] Bioconductor
 ggbeeswarm               0.7.2     2023-04-29 [1] CRAN (R 4.2.2)
 ggExtra                * 0.10.1    2023-08-21 [1] CRAN (R 4.2.2)
 ggforce                  0.4.1     2022-10-04 [1] CRAN (R 4.2.1)
 ggh4x                    0.2.8     2024-01-23 [1] CRAN (R 4.2.2)
 ggplot2                * 3.4.4     2023-10-12 [1] CRAN (R 4.2.2)
 ggplotify              * 0.1.2     2023-08-09 [1] CRAN (R 4.2.2)
 ggraph                 * 2.1.0     2022-10-09 [1] CRAN (R 4.2.1)
 ggrastr                  1.0.2     2023-06-01 [1] CRAN (R 4.2.2)
 ggrepel                  0.9.4     2023-10-13 [1] CRAN (R 4.2.2)
 ggridges                 0.5.6     2024-01-23 [1] CRAN (R 4.2.2)
 GlobalOptions            0.1.2     2020-06-10 [1] CRAN (R 4.2.1)
 globals                  0.16.2    2022-11-21 [1] CRAN (R 4.2.2)
 glue                     1.6.2     2022-02-24 [1] CRAN (R 4.2.1)
 goftest                  1.2-3     2021-10-07 [1] CRAN (R 4.2.1)
 graph                  * 1.76.0    2022-11-01 [1] Bioconductor
 graphlayouts             1.0.0     2023-05-01 [1] CRAN (R 4.2.2)
 gridBase                 0.4-7     2014-02-24 [1] CRAN (R 4.2.1)
 gridExtra              * 2.3       2017-09-09 [1] CRAN (R 4.2.2)
 gridGraphics             0.5-1     2020-12-13 [1] CRAN (R 4.2.1)
 GSEABase               * 1.60.0    2022-11-01 [1] Bioconductor
 gtable                   0.3.4     2023-08-21 [1] CRAN (R 4.2.2)
 gtools                 * 3.9.4     2022-11-27 [1] CRAN (R 4.2.2)
 HDF5Array                1.26.0    2022-11-01 [1] Bioconductor
 hms                      1.1.3     2023-03-21 [1] CRAN (R 4.2.3)
 htmltools                0.5.7     2023-11-03 [1] CRAN (R 4.2.3)
 htmlwidgets              1.6.4     2023-12-06 [1] CRAN (R 4.2.2)
 httpuv                   1.6.9     2023-02-14 [1] CRAN (R 4.2.2)
 httr                     1.4.7     2023-08-15 [1] CRAN (R 4.2.2)
 ica                      1.0-3     2022-07-08 [1] CRAN (R 4.2.1)
 igraph                   1.4.2     2023-04-07 [1] CRAN (R 4.2.3)
 interactiveDisplayBase   1.36.0    2022-11-01 [1] Bioconductor
 IRanges                * 2.32.0    2022-11-01 [1] Bioconductor
 irlba                    2.3.5.1   2022-10-03 [1] CRAN (R 4.2.2)
 iterators                1.0.14    2022-02-05 [1] CRAN (R 4.2.1)
 jsonlite                 1.8.4     2022-12-06 [1] CRAN (R 4.2.2)
 kableExtra             * 1.4.0     2024-01-24 [1] CRAN (R 4.2.2)
 KEGGREST                 1.38.0    2022-11-01 [1] Bioconductor
 KernSmooth               2.23-21   2023-05-03 [1] CRAN (R 4.2.2)
 knitr                  * 1.45      2023-10-30 [1] CRAN (R 4.2.2)
 labeling                 0.4.3     2023-08-29 [1] CRAN (R 4.2.2)
 later                    1.3.1     2023-05-02 [1] CRAN (R 4.2.2)
 lattice                  0.21-8    2023-04-05 [1] CRAN (R 4.2.2)
 lazyeval                 0.2.2     2019-03-15 [1] CRAN (R 4.2.1)
 leiden                   0.4.3.1   2023-11-17 [1] CRAN (R 4.2.2)
 lifecycle                1.0.4     2023-11-07 [1] CRAN (R 4.2.2)
 limma                  * 3.54.2    2023-02-28 [1] Bioconductor
 listenv                  0.9.1     2024-01-29 [1] CRAN (R 4.2.2)
 lmtest                   0.9-40    2022-03-21 [1] CRAN (R 4.2.1)
 locfit                   1.5-9.7   2023-01-02 [1] CRAN (R 4.2.2)
 magrittr               * 2.0.3     2022-03-30 [1] CRAN (R 4.2.1)
 MASS                     7.3-58.3  2023-03-07 [1] CRAN (R 4.2.2)
 Matrix                 * 1.6-5     2024-01-11 [1] CRAN (R 4.2.2)
 MatrixGenerics         * 1.10.0    2022-11-01 [1] Bioconductor
 matrixStats            * 0.63.0    2022-11-18 [1] CRAN (R 4.2.2)
 memoise                  2.0.1     2021-11-26 [1] CRAN (R 4.2.1)
 metapod                  1.6.0     2022-11-01 [1] Bioconductor
 mime                     0.12      2021-09-28 [1] CRAN (R 4.2.1)
 miniUI                   0.1.1.1   2018-05-18 [1] CRAN (R 4.2.1)
 munsell                  0.5.0     2018-06-12 [1] CRAN (R 4.2.1)
 neldermead             * 1.0-12    2022-02-01 [1] CRAN (R 4.2.2)
 nlme                     3.1-162   2023-01-31 [1] CRAN (R 4.2.2)
 NMF                    * 0.26      2023-03-20 [1] CRAN (R 4.2.2)
 openssl                  2.0.6     2023-03-09 [1] CRAN (R 4.2.2)
 optimbase              * 1.0-10    2022-01-26 [1] CRAN (R 4.2.2)
 optimsimplex           * 1.0-8     2022-01-28 [1] CRAN (R 4.2.2)
 parallelly               1.36.0    2023-05-26 [1] CRAN (R 4.2.2)
 patchwork              * 1.2.0     2024-01-08 [1] CRAN (R 4.2.2)
 pbapply                  1.7-2     2023-06-27 [1] CRAN (R 4.2.2)
 pheatmap                 1.0.12    2019-01-04 [1] CRAN (R 4.2.2)
 pillar                   1.9.0     2023-03-22 [1] CRAN (R 4.2.3)
 pkgbuild                 1.4.3     2023-12-10 [1] CRAN (R 4.2.2)
 pkgconfig                2.0.3     2019-09-22 [1] CRAN (R 4.2.1)
 pkgload                  1.3.4     2024-01-16 [1] CRAN (R 4.2.2)
 plotly                 * 4.10.4    2024-01-13 [1] CRAN (R 4.2.2)
 plyr                     1.8.9     2023-10-02 [1] CRAN (R 4.2.2)
 png                      0.1-8     2022-11-29 [1] CRAN (R 4.2.2)
 polyclip                 1.10-4    2022-10-20 [1] CRAN (R 4.2.1)
 popsicleR              * 0.2.1     2023-12-11 [1] Github (bicciatolab/popsicleR@f784754)
 profvis                  0.3.8     2023-05-02 [1] CRAN (R 4.2.2)
 progressr                0.14.0    2023-08-10 [1] CRAN (R 4.2.2)
 promises                 1.2.0.1   2021-02-11 [1] CRAN (R 4.2.1)
 purrr                    1.0.2     2023-08-10 [1] CRAN (R 4.2.2)
 R.methodsS3            * 1.8.2     2022-06-13 [1] CRAN (R 4.2.1)
 R.oo                   * 1.26.0    2024-01-24 [1] CRAN (R 4.2.2)
 R.utils                * 2.12.3    2023-11-18 [1] CRAN (R 4.2.2)
 R6                       2.5.1     2021-08-19 [1] CRAN (R 4.2.1)
 RANN                   * 2.6.1     2019-01-08 [1] CRAN (R 4.2.1)
 rappdirs                 0.3.3     2021-01-31 [1] CRAN (R 4.2.1)
 RColorBrewer           * 1.1-3     2022-04-03 [1] CRAN (R 4.2.2)
 Rcpp                     1.0.11    2023-07-06 [1] CRAN (R 4.2.2)
 RcppAnnoy                0.0.20    2022-10-27 [1] CRAN (R 4.2.1)
 RCurl                    1.98-1.12 2023-03-27 [1] CRAN (R 4.2.3)
 readr                  * 2.1.4     2023-02-10 [1] CRAN (R 4.2.2)
 readxl                 * 1.4.2     2023-02-09 [1] CRAN (R 4.2.2)
 registry               * 0.5-1     2019-03-05 [1] CRAN (R 4.2.1)
 remotes                  2.4.2.1   2023-07-18 [1] CRAN (R 4.2.2)
 reshape2               * 1.4.4     2020-04-09 [1] CRAN (R 4.2.2)
 restfulr                 0.0.15    2022-06-16 [1] CRAN (R 4.2.2)
 reticulate             * 1.28      2023-01-27 [1] CRAN (R 4.2.2)
 rhdf5                    2.42.1    2023-04-07 [1] Bioconductor
 rhdf5filters             1.10.1    2023-03-24 [1] Bioconductor
 Rhdf5lib                 1.20.0    2022-11-01 [1] Bioconductor
 rjson                    0.2.21    2022-01-09 [1] CRAN (R 4.2.1)
 rlang                    1.1.2     2023-11-04 [1] CRAN (R 4.2.2)
 rmarkdown              * 2.26      2024-03-05 [1] CRAN (R 4.2.2)
 rngtools               * 1.5.2     2021-09-20 [1] CRAN (R 4.2.1)
 ROCR                     1.0-11    2020-05-02 [1] CRAN (R 4.2.1)
 Rsamtools                2.14.0    2022-11-01 [1] Bioconductor
 RSpectra                 0.16-1    2022-04-24 [1] CRAN (R 4.2.1)
 RSQLite                  2.3.1     2023-04-03 [1] CRAN (R 4.2.2)
 rstudioapi             * 0.15.0    2023-07-07 [1] CRAN (R 4.2.2)
 rsvd                     1.0.5     2021-04-16 [1] CRAN (R 4.2.1)
 rtracklayer              1.58.0    2022-11-01 [1] Bioconductor
 Rtsne                    0.16      2022-04-17 [1] CRAN (R 4.2.1)
 S4Vectors              * 0.36.2    2023-02-26 [1] Bioconductor
 ScaledMatrix             1.6.0     2022-11-01 [1] Bioconductor
 scales                   1.3.0     2023-11-28 [1] CRAN (R 4.2.2)
 scater                   1.26.1    2022-11-13 [1] Bioconductor
 scattermore              1.2       2023-06-12 [1] CRAN (R 4.2.2)
 scDblFinder            * 1.12.0    2022-11-01 [1] Bioconductor
 scMCA                  * 0.2.0     2023-12-11 [1] Github (ggjlab/scMCA@0ac6b52)
 scQCEA                 * 0.99.1    2024-03-21 [1] Github (isarnassiri/scQCEA@33bd003)
 scran                    1.26.2    2023-01-19 [1] Bioconductor
 sctransform              0.4.1     2023-10-19 [1] CRAN (R 4.2.2)
 scuttle                  1.8.4     2023-01-19 [1] Bioconductor
 session                * 1.0.3     2012-10-29 [1] CRAN (R 4.2.2)
 sessioninfo              1.2.2     2021-12-06 [1] CRAN (R 4.2.1)
 Seurat                 * 4.4.0     2024-02-08 [1] https://satijalab.r-universe.dev (R 4.2.2)
 SeuratObject           * 4.1.4     2024-02-08 [1] https://satijalab.r-universe.dev (R 4.2.2)
 shape                    1.4.6.1   2024-02-23 [1] CRAN (R 4.2.2)
 shiny                    1.8.0     2023-11-17 [1] CRAN (R 4.2.2)
 shinythemes              1.2.0     2021-01-25 [1] CRAN (R 4.2.2)
 SingleCellExperiment   * 1.20.1    2023-03-17 [1] Bioconductor
 SingleR                * 2.0.0     2022-11-01 [1] Bioconductor
 sp                       1.6-0     2023-01-19 [1] CRAN (R 4.2.2)
 sparseMatrixStats        1.10.0    2022-11-01 [1] Bioconductor
 spatstat.data            3.0-4     2024-01-15 [1] CRAN (R 4.2.2)
 spatstat.explore         3.1-0     2023-03-14 [1] CRAN (R 4.2.2)
 spatstat.geom            3.2-1     2023-05-09 [1] CRAN (R 4.2.2)
 spatstat.random          3.1-4     2023-03-13 [1] CRAN (R 4.2.2)
 spatstat.sparse          3.0-1     2023-03-12 [1] CRAN (R 4.2.2)
 spatstat.utils           3.0-3     2023-05-09 [1] CRAN (R 4.2.2)
 statmod                  1.5.0     2023-01-06 [1] CRAN (R 4.2.2)
 stringi                  1.7.12    2023-01-11 [1] CRAN (R 4.2.2)
 stringr                * 1.5.1     2023-11-14 [1] CRAN (R 4.2.2)
 SummarizedExperiment   * 1.28.0    2022-11-01 [1] Bioconductor
 survival                 3.5-5     2023-03-12 [1] CRAN (R 4.2.2)
 svglite                  2.1.2     2023-10-11 [1] CRAN (R 4.2.2)
 systemfonts              1.0.4     2022-02-11 [1] CRAN (R 4.2.1)
 tensor                   1.5       2012-05-05 [1] CRAN (R 4.2.1)
 tibble                   3.2.1     2023-03-20 [1] CRAN (R 4.2.3)
 tidygraph                1.2.3     2023-02-01 [1] CRAN (R 4.2.2)
 tidyr                    1.3.0     2023-01-24 [1] CRAN (R 4.2.2)
 tidyselect               1.2.0     2022-10-10 [1] CRAN (R 4.2.1)
 tweenr                   2.0.2     2022-09-06 [1] CRAN (R 4.2.1)
 tzdb                     0.3.0     2022-03-28 [1] CRAN (R 4.2.1)
 umap                   * 0.2.10.0  2023-02-01 [1] CRAN (R 4.2.3)
 urlchecker               1.0.1     2021-11-30 [1] CRAN (R 4.2.1)
 usethis                * 2.2.3     2024-02-19 [1] CRAN (R 4.2.2)
 utf8                     1.2.3     2023-01-31 [1] CRAN (R 4.2.2)
 uwot                     0.1.14    2022-08-22 [1] CRAN (R 4.2.1)
 vctrs                    0.6.4     2023-10-12 [1] CRAN (R 4.2.2)
 vipor                    0.4.7     2023-12-18 [1] CRAN (R 4.2.2)
 viridis                  0.6.5     2024-01-29 [1] CRAN (R 4.2.2)
 viridisLite              0.4.2     2023-05-02 [1] CRAN (R 4.2.2)
 visNetwork               2.1.2     2022-09-29 [1] CRAN (R 4.2.2)
 withr                    3.0.0     2024-01-16 [1] CRAN (R 4.2.2)
 xfun                     0.39      2023-04-20 [1] CRAN (R 4.2.2)
 xgboost                  1.7.5.1   2023-03-30 [1] CRAN (R 4.2.3)
 XML                    * 3.99-0.14 2023-03-19 [1] CRAN (R 4.2.3)
 xml2                     1.3.3     2021-11-30 [1] CRAN (R 4.2.1)
 xtable                   1.8-4     2019-04-21 [1] CRAN (R 4.2.1)
 XVector                  0.38.0    2022-11-01 [1] Bioconductor
 yaml                     2.3.7     2023-01-23 [1] CRAN (R 4.2.2)
 yulab.utils              0.1.4     2024-01-28 [1] CRAN (R 4.2.2)
 zip                    * 2.2.2     2022-10-26 [1] CRAN (R 4.2.1)
 zlibbioc                 1.44.0    2022-11-01 [1] Bioconductor
 zoo                      1.8-11    2022-09-17 [1] CRAN (R 4.2.1)

**Comment by matteomarchionni** [comment]
Thank you for your report. We have identified an issue with certain dependency versions and have consequently updated them in the installation procedure. It is important to note that due to various changes in dependencies, it is no longer feasible to install all packages in R. We advise following the updated instructions for configuring the anaconda environment to ensure correct installation of the libraries.
